/**
 * Generates `theme.css` — the Tailwind v4 half of this package — from the scales exported by
 * `index.cjs`.
 *
 * Why this exists: the plugin is a plain `addBase` function, and `@plugin` in v4 cannot register
 * theme values. In v3 the scales reach Tailwind through `theme.extend` in a JS config; v4 has no JS
 * config, so without this file `rounded-radius-*` is never generated and the custom container and
 * breakpoint sizes silently fall back to Tailwind's defaults.
 *
 * Generated rather than hand-written so the JS maps stay the single source of truth.
 *
 *   node build-theme.cjs
 */
const fs = require("fs");
const path = require("path");
const { radius, containers, screens } = require("./index.cjs");

const block = (entries) =>
  entries.map(([name, value]) => `  ${name}: ${value};`).join("\n");

// `--radius-radius-lg` is what produces the `rounded-radius-lg` class: v4 builds a utility from the
// namespace (`--radius-`) plus the key (`radius-lg`). The doubled word is the price of keeping the
// class names identical between v3 and v4.
const radiusVars = Object.entries(radius).map(([k, v]) => [`--radius-radius-${k}`, v]);
const containerVars = Object.entries(containers).map(([k, v]) => [`--container-${k}`, v]);
const breakpointVars = Object.entries(screens).map(([k, v]) => [`--breakpoint-${k}`, v]);

const css = `/*
 * TORCH Glare — Tailwind v4 theme scales. GENERATED by build-theme.cjs; do not edit by hand.
 *
 * Usage, alongside the plugin itself:
 *
 *   @import "tailwindcss";
 *   @plugin "glare-torch-mode";
 *   @import "glare-torch-mode/theme.css";
 *
 * Tailwind v3 users do not need this file — they get the same scales from
 * \`theme.extend.borderRadius\` / \`.containers\` and top-level \`screens\` in tailwind.config.js.
 *
 * Two things to know:
 *   - v4 shares the container scale with \`max-w-*\`, so \`--container-md\` also sets \`max-w-md\`.
 *   - The plugin separately sets \`--radius-*\` on \`:root\`, which is v4's own border-radius
 *     namespace. The values match v4's defaults numerically, but they are px where v4 uses rem.
 */
@theme {
  /* Corner radius — mirrors the Figma \`radius/*\` collection. Yields \`rounded-radius-*\`. */
${block(radiusVars)}

  /* Container-query sizes for the \`@md:\` variants used by FieldSection / FormRenderer. */
${block(containerVars)}

  /* Viewport breakpoints. \`sm\` is 600px rather than Tailwind's 640. */
${block(breakpointVars)}
}
`;

fs.writeFileSync(path.join(__dirname, "theme.css"), css);
console.log(
  `theme.css written: ${radiusVars.length} radius, ${containerVars.length} container, ${breakpointVars.length} breakpoint vars`,
);
