name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
          
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
          
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      
      - name: Install missing dependencies
        run: |
          pnpm add embla-carousel embla-carousel-react
          pnpm add -D @types/react-dom
        
      - name: Fix TypeScript import extensions
        run: |
          # More thorough fix for import extensions
          find ./src ./lib -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/from ['"'"'"]\(.*\)\.tsx['"'"'"]/from "\1"/g' || true
          find ./app -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/from ['"'"'"]\(.*\)\.tsx['"'"'"]/from "\1"/g' || true
          
      - name: Set consistent Next.js version
        run: |
          # Use exact same Next.js version as remote server
          pnpm add next@15.1.7
        
      - name: Update TypeScript config
        run: |
          # Allow importing TypeScript extensions
          if [ -f tsconfig.json ]; then
            sed -i 's/"compilerOptions": {/"compilerOptions": {\n    "allowImportingTsExtensions": true,/g' tsconfig.json
          fi
        
      - name: Lint code
        run: pnpm lint || true
        
      - name: Build project
        run: pnpm build
        
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            cd /home/admin/Torch-Glare-Website
            git pull
            if ! command -v pnpm &> /dev/null; then
              npm install -g pnpm
            fi
            pnpm install --no-frozen-lockfile
            pnpm add embla-carousel embla-carousel-react
            pnpm add -D @types/react-dom
            
            # Fix TypeScript import extensions on server
            find ./src ./lib -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/from ['"'"'"]\(.*\)\.tsx['"'"'"]/from "\1"/g' 2>/dev/null || true
            find ./app -type f -name "*.tsx" -o -name "*.ts" | xargs sed -i 's/from ['"'"'"]\(.*\)\.tsx['"'"'"]/from "\1"/g' 2>/dev/null || true
            
            pnpm build
            pm2 restart glare-website || pm2 start npm --name "glare-website" -- run start
            
      - name: Health check
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT || '22' }}
          script: |
            sleep 10
            if ! curl -s -f http://localhost:3000 > /dev/null; then
              echo "Health check failed! Application is not responding."
              echo "Deployment failed at $(date)" >> /home/admin/deploy-errors.log
              exit 1
            else
              echo "Deployment successful at $(date)" >> /home/admin/deploy-success.log
            fi
            
  notify:
    needs: deploy
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Notify deployment status
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: deployments
          SLACK_COLOR: ${{ needs.deploy.result == 'success' && 'good' || 'danger' }}
          SLACK_TITLE: Deployment ${{ needs.deploy.result == 'success' && 'Successful' || 'Failed' }}
          SLACK_MESSAGE: 'Torch-Glare-Website deployment to production ${{ needs.deploy.result }}'
          SLACK_FOOTER: 'GitHub Actions'
        if: env.SLACK_WEBHOOK != ''
